name: Auto Insights to Slack

on:
  push:
    branches:
      - master  # Runs when pushing to the main branch
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      max_attempts: 3  # Retries the entire job up to 3 times if it fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Retry Database Connection (5 attempts)
        run: |
          for i in {1..5}; do
            echo "Attempt $i to connect to the database..."
            PGPASSWORD=${{ secrets.DB_PASS }} psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -p ${{ secrets.DB_PORT }} -c "\dt" && break
            echo "Database connection failed. Retrying in 10 seconds..."
            sleep 10
          done
        shell: bash

      - name: Run insights script
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: python main.py
