name: Auto Insights to Slack

on:
  push:
    branches:
      - master  # Runs when pushing to the main branch
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run insights script with retries
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          attempts=0
          max_attempts=5
          until python main.py || [ $attempts -ge $max_attempts ]; do
            echo "Attempt $((attempts+1)) failed. Retrying in 10 seconds..."
            attempts=$((attempts+1))
            sleep 10
          done
          if [ $attempts -ge $max_attempts ]; then
            echo "Script failed after $max_attempts attempts."
            exit 1
          fi
